### ISSUE TITLE
Added task 04 (tasks from S. +)

### ISSUE THREAD

**Issue by Cyberlox** [Cyberlox/JR#2]
Проверяю заливку на Гит и issues (самостоятельно помню ли)
+ таск 4
+ таски от Саши

**Comment by r-annie** [comment]
Решения приняты.
![Screenshot_20220530-073408_GitHub.jpg](https://user-images.githubusercontent.com/84032256/170912511-2b39c9cb-2203-46e0-b0a9-430e9fdfe455.jpg)
Таски 0103, 0104 и 0106 переместить в соответствующую папку
Таски 012, 013 переименовать и тоже переместить
После этого можно закрывать issue.

**Comment by r-annie** [comment]
Done.
